version: '3'
services:
    web:
        build: .
        ports:
            - "80:80"
        links:
            - frontend
        networks:
            - dockernet
    frontend:
        build:
            context: ./frontend
        ports:
            - "8080:8080"
        networks:
            - dockernet
networks:
    dockernet:
        driver: "bridge"
